<script lang="ts">
	let { data } = $props()

	import { page } from '$app/stores'
	import { onMount } from 'svelte'
	import { ChevronsLeft, Menu } from 'lucide-svelte';
	import MediaQuery from "$lib/components/mediaQuery.svelte";

	import '../docs.css'

	let show_toc = false;

	// function updateLeftMenu(event) {
	// 	const li_elements = document.getElementById('docs-menu-on-left').querySelectorAll('li')
	// 	li_elements.forEach(li => {
	// 		const a = li.querySelector('a')
	// 		if (a != null) {
	// 			a.classList.remove("select-current-page")
	// 		}
	// 	})
	// 	event.target.classList.add("select-current-page")
	// }

	function createTocListItem(parent_element, padding_class, id, content) {
		const li = document.createElement('li');
		const a = document.createElement('a');

		li.classList.add('aaa');

		a.className = padding_class;
		a.href = '#' + id;
		a.setAttribute('uk-scroll', '');
		a.textContent = content;

		li.appendChild(a);
		parent_element.appendChild(li);
	}

	function generateTableOfContents() {
		console.log("Generating Table of contents")
		const headers = document.querySelectorAll("h1, h2, h3, h4")
		if (headers.length > 1) {
			// const toc_ul = document.getElementById('toc-ul')
			const toc_uls = document.querySelectorAll('.toc-ul');
			toc_uls.forEach(toc_ul => {
				const menu_heading_li = document.createElement('li');
				menu_heading_li.className = 'menu-heading';
				menu_heading_li.textContent = 'Table of contents'
				toc_ul.appendChild(menu_heading_li)
				headers.forEach(h_el => {
					if ( ["h1", "h2", "h3", "h4"].indexOf(h_el.tagName.toLowerCase()) > -1 ) {
						if ( h_el.id ) {
							const padding_class = `${h_el.tagName.toLowerCase()}-toc-padding`;
							createTocListItem(toc_ul, padding_class, h_el.id, h_el.textContent);
							// if ( h_el.tagName.toLowerCase() == 'h2' ) {
							// 	createTocListItem(toc_ul, padding_class, h_el.id, h_el.textContent, " └ ")
							// } else if ( h_el.tagName.toLowerCase() == 'h3' ) {
							// 	createTocListItem(toc_ul, padding_class, h_el.id, h_el.textContent, "\u00A0\u00A0\u00A0└ ")
							// } else if ( h_el.tagName.toLowerCase() == 'h4' ) {
							// 	createTocListItem(toc_ul, padding_class, h_el.id, h_el.textContent, "\u00A0\u00A0\u00A0. ")
							// } else {
							// 	createTocListItem(toc_ul, padding_class, h_el.id, h_el.textContent)
							// }
							// toc_html += `<li><a ${padding_class} href="#${header.id}" uk-scroll>${header.textContent}</a></li>\n`
						}
					}
				})
			});
			show_toc = true;
		}	else {
			show_toc = false;
		}
	}

	function refreshTableOfContents() {
		console.log("Refreshing Table of contents. Removing elements")
		const toc_uls = document.querySelectorAll('.toc-ul')  // need to update two places
		toc_uls.forEach( toc_ul => {
			toc_ul.replaceChildren() // delete all existing li elements
		});
		generateTableOfContents()
	}

	onMount(async () =>{
		 // Highlight current page in the menu
		const li_elements = document.getElementById('docs-menu-on-left').querySelectorAll('li')
		li_elements.forEach( li => {
			const a = li.querySelector('a')
			if ( a != null ) {
				if ( a.outerHTML.includes(data.slug) ) {
					a.classList.add("select-current-page")
				}
			}
		})
	})
</script>

<div class="docs-main">

	<!-- Off Canvas TOC -->
	<div id="offcanvas-toc" uk-offcanvas="flip:true">
		<div class="uk-offcanvas-bar">	
			<button class="uk-offcanvas-close" type="button" uk-close></button>
				<div class="toc">
					<ul class="toc-ul -ml-8">
						<!-- list items will be generated by code -->
					</ul>
				</div>
			</div>
	</div>

	<!-- Responsive Button -->
	<MediaQuery query="(max-width: 850px)" let:matches>
		{#if matches && show_toc}
			<div>
				<button class="right-sidebar-toggle" aria-label="Show table of contents">
					<a href="#offcanvas-toc" uk-toggle><ChevronsLeft style="min-width:1rem" /></a>
				</button>
			</div>
		{/if}
	</MediaQuery>

	<div class="main-inner">
		<div class="sidebar-left">
			<!-- <div class="docs-menu-on-left" id="docs-menu-on-left">
				<ul>
					<li class="menu-heading">Characters Documentation</li>
						{#each data.docs as doc}
							<li><a onclick={updateLeftMenu} href="/docs/unreal-characters/{doc.doc_slug}">{doc.title}</a></li>
						{/each}
				</ul>
			</div> -->
		</div>
		<div class="content">	
			<svelte:component this={data.content} callbackAfterUpdate={refreshTableOfContents} />
		</div>
		<div class="sidebar-right">
			<div class="toc">
				<ul class="toc-ul">
					<!-- list items will be generated by code -->
				</ul>
			</div>
		</div>
	</div>
</div>

<style>
</style>